Algoritmo "pares_consecutivos"

Var
   x, soma: inteiro


Inicio
    escreval("Digite um numero inteiro: ")
    leia(x)
    
    enquanto x <> 0 faca
     se x % 2 <> 0 entao
      x <- x + 1
       soma <- 5 * x + 20
        senao
         soma<- 5 * x + 20
      fimse
      
      escreva("SOMA= ",soma)
      leia(x)
        

        
      fimenquanto
      



Fimalgoritmo